# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  scrum-postgres:
    image: "demo7"
    container_name: demo7
    #Volume mounted for database for the storage
    volumes:
      - demo:/var/lib/postgresql/data
    ports:
      - 5435:5435 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789

  #Back-end Spring Boot Application
  scrum-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./target
    container_name: target

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=scrum-postgres
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    ports:
      - 8090:8090 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - scrum-postgres

